### ISSUE TITLE
Not receiving responses with bloomfilters

### ISSUE THREAD

**Issue by seik** [devos50/libtorrent-swarm-health#1]
Hi, sorry for opening an issue on a POC and old project.

I have been trying to use this code to get seeders and leechers but `dht_pkt_alert` comes always without bloomfilters (`[r][BFsd]` and `[r][BFpe]`). I have ported the code to python3 and asyncio: https://gist.github.com/seik/e998f2987b7f63660de259fe815b91d2. I receive alerts so I guess there are no problems with my network.

If you could give me some insight it will help me a lot with my research.

Thanks.

**Comment by devos50** [comment]
Hi!

No problem for responding on this project. By default, `dht_pkt_alert` messages do not include bloom filters. They are only embedded by other peers when the `scrape` flag is set in libtorrent. Unfortunately, this flag cannot be set from Python code since there are no bindings for it. Therefore, we have used a modified version of libtorrent, also see [this commit](https://github.com/devos50/libtorrent/commit/69fbac472c8d5767a084285976735a32767ef3d7). I recommend to port these changes to a later version of libtorrent, recompile libtorrent + Python libraries, and try again.

Please let me know if that works for you 👍

**Comment by seik** [comment]
Ok thanks! Will try that. Thank you 😄
